### ISSUE TITLE
As a Safety Driver, I want to see a map with my position and the position of the interchange point

### ISSUE THREAD

**Issue by tomcory** [TU-CP18/cp18-app#10]
**Back-end twin:**
TU-CP18/cp18-daimler-backend#19

**Description:**
As a driver I want to navigate to my assigned car before I start my shift.

**Acceptance criteria:**

- [x] create a map view
- [x] implement geolocation permission
- [x] mark vehicle intercept location on map 
- [x] draw road from current location to intercept location

**Comment by calvinschmidt** [comment]
The map view acceptance criteria is implemented, see #31. I'll hand this issue over to Q&A.

**Comment by nschoen** [comment]
Closed, the map now shows the actual interchange of the next shift and the migration to mapbox is covered in #45.
