### ISSUE TITLE
As a Safety Driver, I want to confirm my arrival at the interchange point.

### ISSUE THREAD

**Issue by tomcory** [TU-CP18/cp18-app#11]
**Back-end twin:**
TU-CP18/cp18-daimler-backend#20

**Description:**

The safety driver should be able to confirm his arrival at the vehicle when he is close to the interception point.

**Acceptance criteria:**

- [x] confirm arrival button is shown inside map view
- [x] arrival button is only shown if current location is closer than 20 meters to destination
- [x] arrival button disappears if distance to location becomes greater than 20 meters
- [x] once the confirmal button is clicked, the user is redirected to the inspect vehicle screen

**Comment by calvinschmidt** [comment]
The acceptance criteria is implemented, see #31. I move the issue to Q&A for acceptance testing.

**Comment by nschoen** [comment]
Works like intended. The update of the internal progress will be handled in #42. I created a new issue to connect the confirm button with the backend in #47. I will close this.
