### ISSUE TITLE
Presence Check: Open the vehicle

### ISSUE THREAD

**Issue by tomcory** [TU-CP18/cp18-app#13]
As a Safety Driver, I want to use my phone to open the vehicle.

**Description:**
Compare GPS of car and SD
Check that the safety driver is assigned to that car on a shift.

**Acceptance criteria:**
- [x] Provide button to open the car
- [x] Request that the user inspected the exterior of the car accordingly
- [x] Call API endpoint to authorise this request and track the event
- [x] Set internal mode to "internal_inspection"

**Comment by nschoen** [comment]
The backend has to provide an "car opening" endpoint before we can continue here.

**Comment by calvinschmidt** [comment]
The frontend part in the app will be done by myself and the new api endpoint will be created by @jonathanba.
The backend should do the following checks:
- check if safety driver is currently assigned to a shift
- check if safety driver is in intercept vehicle state
- optional: check if sent GPS location nearly matches the current location of the car (ca. 20 meters)

**Comment by calvinschmidt** [comment]
The frontend part is done. The backend part is tracked in the following issue https://github.com/TU-CP18/cp18-backend/issues/117
