### ISSUE TITLE
As a Safety Driver, I want to view the location of my next assignment on a map.

### ISSUE THREAD

**Issue by tomcory** [TU-CP18/cp18-app#16]
**Back-end twin:**
TU-CP18/cp18-daimler-backend#30

**Description:**

Inside the splash screen of the app, the safety driver should see a map view with a marker in it that marks the location where the next shift starts.

**Acceptance criteria:**

- [x] provide map view with marker of location
- [x] retrieve information of next shift
- [x] integrate map view into splash screen

**Comment by calvinschmidt** [comment]
The map view with the marker is provided through a new component called `MapMarker`, see #31.

**Comment by calvinschmidt** [comment]
@captainsano implemented the splash screen with pr #30. Thus, I move this issue to Q&A for acceptance testing.
