### ISSUE TITLE
As a Safety Driver, I want to switch to manual driving mode in case the autonomous driving software makes a wrong decision or an unpredicted event occurs, so that I can prevent an accident.

### ISSUE THREAD

**Issue by calvinschmidt** [TU-CP18/cp18-app#17]
**Back-end twin:**

TU-CP18/cp18-daimler-backend#23

**Description:**

**Acceptance criteria:**

- [ ]
- [ ]

**Comment by nschoen** [comment]
Closed, this issue is not relevant any more. The car will not provide a manual mode. Instead an emergency button will be implemented in #19 and an emergency mode is covered in #48
