### ISSUE TITLE
Implement splash screen

### ISSUE THREAD

**Issue by nschoen** [TU-CP18/cp18-app#25]
**Description:**
Implement the splash screen where the safety driver can see/follow his/her assignments and open the navigation, schedule list and the fleet manager contact screen.

**Acceptance criteria:**

- [x] Show current assignment
- [x] Show navigation button/icons to schedule list and fleet manager contact screen 
- [x] Show preview of the map

**Comment by calvinschmidt** [comment]
This issue is related to #12 and #16.
