### ISSUE TITLE
Chat (FM+SD)

### ISSUE THREAD

**Issue by clemenspeters** [TU-CP18/cp18-app#26]
**Back-end twin:**

**Description:**
As a driver I want to chat with my fleet manager at every stage.

Related backend ticket: https://github.com/TU-CP18/cp18-backend/issues/45

**Acceptance criteria:**

- [x] Push notifications on incoming messages
- [x] Messages can be sent to the fleet manager
- [x] Chat History is available

**Comment by clemenspeters** [comment]
screen/HomeScreen.js has a button (will make a call) (this.props.navigation.navigate('Contact')
screen/ContactScreen.js is emtpy and can be used
navigation/MainNavigation.js Contact:ContactScreen

store -> observable?? (websocket)

react state oder mobx state ?

**Comment by clemenspeters** [comment]
https://github.com/FaridSafi/react-native-gifted-chat

**Comment by clemenspeters** [comment]
For Push notifications:
Maybe we can use AWS SNS: https://medium.com/@thexap/show-push-notifications-on-react-native-app-a613a5a2c159

**Comment by nschoen** [comment]
> screen/HomeScreen.js has a button (will make a call) (this.props.navigation.navigate('Contact')
> screen/ContactScreen.js is emtpy and can be used
> navigation/MainNavigation.js Contact:ContactScreen
> 
> store -> observable?? (websocket)
> 
> react state oder mobx state ?

You can use mobx state. Create a store, start listening, provide an action to send messages and add incoming message to an mobx array. In this way we separate the UI from the logic and can reuse it. Additionally when the chat screen is closed we can still receive messages for example to show notifications.

**Comment by nschoen** [comment]
Push notifications is maybe an overkill. Maybe we can run some background tasks when the app is closed (but not completely killed) and show local notifications which would also be suitable for the awareness check when the app is in the background/phone is sleeping.

**Comment by calvinschmidt** [comment]
If it's only about local notifications, I'd recommend to use the api from expo: https://docs.expo.io/versions/v32.0.0/sdk/notifications/
They also support push notifications if necessary: https://docs.expo.io/versions/latest/guides/push-notifications/

**Comment by clemenspeters** [comment]
merge master here

**Comment by clemenspeters** [comment]
Ist soweit fertig. History wird geladen. @nschoen kannst du mal schauen wegen der Konflikte beim Mergen 😕 ?

**Comment by nschoen** [comment]
Merged
