### ISSUE TITLE
Provide an emergency screen for the ride mode 

### ISSUE THREAD

**Issue by nschoen** [TU-CP18/cp18-app#48]
**Description:**
Refs #19. When the emergency button is clicked (in the app or the car) the emergency mode should be activated which indicates that the car is currently in emergency mode. This screen should also provide a contact buttons to contact the fleet manager immediately. Optionally there can be a button to restart the ride which may should be confirmed by the Fleet Manager.

**Acceptance criteria:**

- [ ] Show emergency mode when button is clicked
- [ ] Emergency mode is clearly indicated (red color)
- [ ] Emergency mode provides a contact button to contact the FM
- [ ] Optional: Provide button to restart ride
- [ ] Optional: Receive emergency mode from the backend so that it can be activated from the backend side (polling or websocket)

**Comment by clemenspeters** [comment]
Optional
