### ISSUE TITLE
Revise idle screen

### ISSUE THREAD

**Issue by nschoen** [TU-CP18/cp18-app#53]
**Description:**
Adapt design, add a simple settings menu with information about the logged in user and a logout button. Additionally the the information for the upcoming/next shift should be more clear and contain a proper formatted address of the interchange point and time.

**Acceptance criteria:**

- [x] Adapt design to the rest of the app
- [x] Use address instead of lat and long for the interchange point
- [x] Format the time
- [x] Setup setting screen with a single logout button
- [x] Connect the logout button (gears) with a settings screen
- [ ] ~~Optional: Enhance settings screen, add user information for example.~~

**Comment by calvinschmidt** [comment]
I finished the point "Use address instead of lat and long for the interchange point" with #58
